### ISSUE TITLE
CORS error because of autogenerated .dev.vars file

### ISSUE THREAD

**Issue by j3sch** [timothymiller/t4-app#103]
Bun autogenerates the .dev.vars file and overrides the values after every install. It takes the keys and values from the `.env.local` file.
In the `.env.local` the keys are named `NEXT_PUBLIC_APP_URL`, but in the `.dev.vars` file it must be `APP_URL`.  Therefore I get the error `APP_URL is not set. CORS errors may occur.` displayed.

**Comment by timothymiller** [comment]
This has been fixed in a previous PR. Please try it again in the latest master branch, and let me know how it works.

**Comment by j3sch** [comment]
nice, now it works perfect. Thank you!
