### ISSUE TITLE
Confusion with T3

### ISSUE THREAD

**Issue by iamshanvy** [timothymiller/t4-app#110]
Hey everyone, first and foremost, cool project, been following for a while!

I would like to raise a concern about the confusion that is happening in the community, a number of users of this project mistakenly associate this project with [t3](https://github.com/t3-oss/create-t3-app) due to the very similar naming. Although the readme clearly states the author of the project, it's much less clear on the website.

I would like to propose a simple resolution in the form of FAQ section on the project's main page and readme file. It could clearly state that this project is not affiliated with, associated with, or endorsed by t3.

I believe proposed change will beneficial for the community, save confusion and will help in maintaining the distinct identities of both projects. I am more than willing to assist in drafting or refining FAQ section if needed.

appreciate all maintainers for the hard work!

![image](https://github.com/timothymiller/t4-app/assets/138781964/613c6692-a1df-4ca6-b43c-1fed9443c6f4)

**Comment by t3dotgg** [comment]
I get questions about this project at least once a day from people assuming it's part of my open source crew. The previous justification for the name isn't even true anymore since TurboRepo was dropped.

![image](https://github.com/timothymiller/t4-app/assets/6751787/9d41a1d0-9c80-48f2-ac84-74388b37dccb)

While I appreciate the suggestion of making clearer call outs on the site and readme, I have been around enough to know nobody reads those. As long as this project is named "T3 + 1", it will be assumed to be part of the t3-oss crew's work. I think rebranding this project is the best faith path forward.

**Comment by albbus-stack** [comment]
> I get questions about this project at least once a day from people assuming it's part of my open source crew. The previous justification for the name isn't even true anymore since TurboRepo was dropped.
> 
> ![image](https://github.com/timothymiller/t4-app/assets/6751787/9d41a1d0-9c80-48f2-ac84-74388b37dccb)
> 
> While I appreciate the suggestion of making clearer call outs on the site and readme, I have been around enough to know nobody reads those. As long as this project is named "T3 + 1", it will be assumed to be part of the t3-oss crew's work. I think rebranding this project is the best faith path forward.

Yeah the original name of the stack doesn't hold up anymore (the bun update was one month ago so this thing is pretty fresh).

The fact that people don't read is also very true (kinda depressing but that's the audience nowadays even on github).

I'm clearly not opposed in any way in changing name but I'm not the one to decide 😅

**Comment by mcalhoun** [comment]
> I get questions about this project at least once a day from people assuming it's part of my open source crew. The previous justification for the name isn't even true anymore since TurboRepo was dropped.
> 
> ![image](https://user-images.githubusercontent.com/6751787/283595322-9d41a1d0-9c80-48f2-ac84-74388b37dccb.jpeg)
> 
> While I appreciate the suggestion of making clearer call outs on the site and readme, I have been around enough to know nobody reads those. As long as this project is named "T3 + 1", it will be assumed to be part of the t3-oss crew's work. I think rebranding this project is the best faith path forward.

I personally don’t think there’s confusion between the two project names anymore than I would think that @t3dotgg created the D3 visualization library because it’s a letter plus a three that sound like each other. IMHO, it’s a bit of an overreach to ask this project to rebrand because of this. I also don’t think Google created the k9s console or that Mark Andreessen’s firm has anything to do with Kubernetes because they used the same first letter/num chars/last letter abbreviation. Naming is hard.

**Comment by tadeumaia** [comment]
And here in my corner, I thought everyone was just ripping off Microsoft (2005).

https://en.wikipedia.org/wiki/Text_Template_Transformation_Toolkit

**Comment by lofimichael** [comment]
There was definitely some initial confusion on my end (especially with T3 Turbo - https://github.com/t3-oss/create-t3-turbo) with React Native. Though I wholly believe that many projects existing in open source is marvelous (and the overall goal), there should be some delineation between them that lets us quicker understand the ecosystem options (with different maintainers and differing levels of opinionation).

**Comment by keylesss** [comment]
> > I get questions about this project at least once a day from people assuming it's part of my open source crew. The previous justification for the name isn't even true anymore since TurboRepo was dropped.
> > ![image](https://user-images.githubusercontent.com/6751787/283595322-9d41a1d0-9c80-48f2-ac84-74388b37dccb.jpeg)
> > While I appreciate the suggestion of making clearer call outs on the site and readme, I have been around enough to know nobody reads those. As long as this project is named "T3 + 1", it will be assumed to be part of the t3-oss crew's work. I think rebranding this project is the best faith path forward.
> 
> I personally don’t think there’s confusion between the two project names anymore than I would think that @t3dotgg created the D3 visualization library because it’s a letter plus a three that sound like each other. IMHO, it’s a bit of an overreach to ask this project to rebrand because of this. I also don’t think Google created the k9s console or that Mark Andreessen’s firm has anything to do with Kubernetes because they used the same first letter/num chars/last letter abbreviation. Naming is hard.

I second this reply. The idea that clear call outs on the site and readme is insufficient is a horrible precedent to set, imo. Especially since it is an OSS project. Not to mention it has now been tweeted out to his 100k+ followers and posted in both community discords.c

Unfortunately, this is not the first time this creator has lashed out publicly over something trivial: https://twitter.com/t3dotgg/status/1625806139630972929?s=46&t=AN-8DvtpD-FtpNs3rv6E2A 

I suggest the maintainers close this issue and pay it no further mind.

**Comment by t3dotgg** [comment]
> I personally don’t think there’s confusion between the two project names anymore than I would think that @t3dotgg created the D3 visualization library because it’s a letter plus a three that sound like each other. IMHO, it’s a bit of an overreach to ask this project to rebrand because of this. I also don’t think Google created the k9s console or that Mark Andreessen’s firm has anything to do with Kubernetes because they used the same first letter/num chars/last letter abbreviation. Naming is hard. 

@mcalhoun, if T3 was an alternative way of building charts, the T3 name would be inappropriate.

It is obvious that this project is built as an alternative to create-t3-app. All but 2 of its followers also follow me. I get asked every day about my "new project" T4.

It is obvious this project is trying to coast off of my likeness. I think that's inappropriate. Clearly many others agree. Hopefully @timothymiller will have something to say eventually.

**Comment by mcalhoun** [comment]
Would you then agree, @t3dotgg, that `tRPC` is coasting off the success/likeness/name built by `gRPC` and should be renamed? 

Open source has always generated "alternatives" that sound like the originals...we have had MEAN/MERN/MEEN stack,  Javascript/Coffeescript/Typescript, and countless others that sound the same but are a "slight variation" to the original name, while also giving a nod/tribute to the original name.

FWIW, I have nothing to do with either project (t3-app or t4-app),  I am  just an opinionated, long-time OSS consumer and maintainer who generally enjoys your (@t3dotgg) content, but my personal opinion here is that your request is an unreasonable one.

**Comment by timothymiller** [comment]
This request lacks merit and does not hold any validity.

I strongly object to the use of profanity in the direct messages that have been sent to me. Such language is disrespectful, inappropriate, and goes against our established code of conduct.

I must insist that you immediately cease the ongoing harassment campaign, as it not only violates our code of conduct but also poses a significant threat to the safety and well-being of our community members.

**Comment by t3dotgg** [comment]
For the record, the only thing close to profanity I've DM'd Tim is "this fkn sucks"

![image](https://github.com/timothymiller/t4-app/assets/6751787/ee8d8a95-8d00-42d7-aac7-9c15cb10e359)
