### ISSUE TITLE
Lucia branch: After pw reset, redirect to /login is 404, it should be /sign-in

### ISSUE THREAD

**Issue by Boscop** [timothymiller/t4-app#131]
After the user clicks the pw reset button, there's this redirect:
https://github.com/timothymiller/t4-app/blob/325b5e58a39bf9cd4019db6273ad6ce62889cf2d/packages/app/features/password-reset/screen.tsx#L18
which results in 404.
The login screen is at `/sign-in`.

**Comment by timothymiller** [comment]
Fixed!
