### ISSUE TITLE
 Expo is starting to support MacOS, is Tauri still going to be need (for MacOS)?

### ISSUE THREAD

**Issue by MatthiasGrandl** [timothymiller/t4-app#140]
See title. I want to build a lightweight native MacOS app and would prefer not to use Tauri. Is this going to be supported by T4?

**Comment by timothymiller** [comment]
Today it's possible to build an iPhone / iPad app that runs on the Apple Silicon Macs with T4.

Depends on what you're looking for. Are you looking for a menu-bar type app?

**Comment by MatthiasGrandl** [comment]
No I was asking about proper MacOS support as it’s being added to Expo. But I already started with a different approach, so I am closing this.
