### ISSUE TITLE
supabaseUrl is required

### ISSUE THREAD

**Issue by joshuabalduff** [timothymiller/t4-app#145]
Hello, I cant seem to get around the error `supabaseUrl is required`  issue besides setting it manually in the client.ts.

Are we missing docs on this or am I missing something?

Thanks!

**Comment by albbus-stack** [comment]
Docs are coming in the next few days. In the meantime you should set your envs in `.env.local` without the `NEXT_PUBLIC` prefix and run `bun install` again. Remember to run an install evertime you change the env file. If this is not it let me know, happy hacking 🤘

**Comment by albbus-stack** [comment]
New docs just dropped [here](https://docs.t4stack.com), refer to that for an in depth explanation of how environment variables work in T4. Closing this for now.
