### ISSUE TITLE
Problems with tamagui styles on Cloudflare pages 

### ISSUE THREAD

**Issue by darthwade** [timothymiller/t4-app#36]
Hi @timothymiller 

Thank you so much for your work on T4. Amazing stack!
I have a question, after deployment to Cloudflare pages based on your docs, I see next:
https://zeus-3v5.pages.dev

Could you pls help me in what direction should I dig?
Thanks once more

**Comment by darthwade** [comment]
Btw, during deployment I also encountered "Error: Could not access built-in Node.js modules. Please make sure that your Cloudflare Pages project has the 'nodejs_compat' compatibility flag set."

adding `node_compat` to `wrangler.toml` didn't help, but applying node_compat via CF dashboard helped
```
[env.preview]
name = "zeus-web-preview"
workers_dev = true
node_compat = true
compatibility_flags = [ "nodejs_compat" ]

[env.production]
name = "zeus-web"
route = "zeus-3v5.pages.dev/*"
workers_dev = false
node_compat = true
compatibility_flags = [ "nodejs_compat" ]
```

**Comment by timothymiller** [comment]
Yep you have to set `node_compat` via the CF dashboard. I'm open to solutions that make that process programatic.

Do you have optimizeCSS set in `next.config.js`? Turn it off if you do.

**Comment by darthwade** [comment]
<img width="775" alt="image" src="https://github.com/timothymiller/t4-app/assets/2220776/634901d7-6fa9-4f14-9d6c-fe384af8a341">
disabled

**Comment by timothymiller** [comment]
That's strange. Ensure your fork is up to date with the main branch and re-deploy.

**Comment by darthwade** [comment]
will do, I created it yesterday via `pnpm create t4-app`

**Comment by darthwade** [comment]
Updated to latest version from `main` branch, so probably there's some problem during building or deployment/cf configuration
https://zeus-3v5.pages.dev

**Comment by timothymiller** [comment]
Make sure your CF deployment is set to node 18!

**Comment by darthwade** [comment]
Strange, recreated cf project from scratch with NODE_VERSION 18 env var, but still same problem https://zeus-web.pages.dev
<img width="406" alt="image" src="https://github.com/timothymiller/t4-app/assets/2220776/694f6e7b-5366-4be9-9c91-68b39c116a5f">

**Comment by darthwade** [comment]
After adding `TAMAGUI_TARGET=web` it finally works :) 
@timothymiller thanks for help!
```
"dev": "TAMAGUI_TARGET=web pnpm with-env next dev",
"build": "TAMAGUI_TARGET=web pnpm with-env next build",
"start": "TAMAGUI_TARGET=web pnpm with-env next start",
```

**Comment by timothymiller** [comment]
@darthwade This was originally set, it must have been removed by a recent PR.

I added it back so other people don't experience this. Thanks for debugging!
