### ISSUE TITLE
[Bug] Expo android apk doesn't start

### ISSUE THREAD

**Issue by albbus-stack** [timothymiller/t4-app#42]
The apk downloaded from the latest expo build comment is not starting and it's giving an error about `expo-updates` not being configured correctly as shown in the log below:

![Screenshot_2023-07-30-11-52-18-648_com.miui.bugreport.jpg](https://github.com/timothymiller/t4-app/assets/57916483/2efefa5b-da18-48fc-b850-2f99e4a8f1c3)

I'm going to try on some of the previous builds and see if they work.

I think this is related to https://github.com/expo/eas-cli/issues/1951 and https://github.com/expo/expo/issues/21238

**Comment by timothymiller** [comment]
I've experienced this for the past week.

It could be related to expo 49. I tried the fixes recommended in the github issue to no avail.

I'll bring it up in next expo office hours

**Comment by timothymiller** [comment]
Possibly related: https://github.com/expo/expo/issues/23382

**Comment by timothymiller** [comment]
According to expo office hours, this project was configured for classic updates. I migrated it to the newer expo-updates implementation.

https://docs.expo.dev/eas-update/migrate-from-classic-updates/?redirected

Should test to see if it fixes things.

**Comment by albbus-stack** [comment]
> According to expo office hours, this project was configured for classic updates. I migrated it to the newer expo-updates implementation.
> 
> https://docs.expo.dev/eas-update/migrate-from-classic-updates/?redirected
> 
> Should test to see if it fixes things

I'll test the apk once it finishes building 👍🏻

**Comment by albbus-stack** [comment]
Now it shows this screen:

![Screenshot_2023-08-03-10-39-12-239_com.t4.app.jpg](https://github.com/timothymiller/t4-app/assets/57916483/4b05f00d-3f38-4d95-8ab6-9f3788d078d7)

**Comment by timothymiller** [comment]
That's dev mode. We need preview or prod to build as part of EAS CI/CD

**Comment by timothymiller** [comment]
It's also much bigger as the dev build. It should be ~25mb in preview and prod

**Comment by timothymiller** [comment]
Since this does start, I'm going to mark this as complete

**Comment by albbus-stack** [comment]
@timothymiller We probably want to change it to preview I think, to output a bundled apk/ipa.

**Comment by superjose** [comment]
I'm having the same problem:

Bare app
expo: 0.46
expo-updates: 0.14.5

We have expo-updates disabled in app.json
