### ISSUE TITLE
webstorm extension

### ISSUE THREAD

**Issue by grmkris** [timothymiller/t4-app#46]
would it be hard to port vscode extension to webstorm as well?

**Comment by timothymiller** [comment]
Do they have an app store like VS Code? Can you link to it?

**Comment by grmkris** [comment]
https://plugins.jetbrains.com/webstorm

**Comment by timothymiller** [comment]
What do you think @albbus-stack? 

He made the vs code extension

**Comment by albbus-stack** [comment]
Sure, I'm gonna reasearch it when I refactor the extension 👍🏻

**Comment by timothymiller** [comment]
I'll add this to the wish list portion of the docs
