### ISSUE TITLE
VSCode extension should generate component name with PascalCase

### ISSUE THREAD

**Issue by ilumin** [timothymiller/t4-app#57]
When I enter the screen name in `t4-app-tools: New Screen` with 

- `CreateTransaction` -- component name generate as `createtransaction` 
- `Create Transaction` -- cannot generate 
- `create-transaction` -- component name generate as `create-transaction`

I think all input should generate into PascalCase, which is `CreateTransaction`

**Comment by albbus-stack** [comment]
Yeah sure, it's a very useful feature so, when I'm back, I'm gonna implement it asap 🤟
