### ISSUE TITLE
Mobius (E2E TS graphql client) support

### ISSUE THREAD

**Issue by geoman2** [timothymiller/t4-app#58]
Hi, mobius is a typed graphql client, part of the Elysia framework, similar to Hono and compatible with it, just has been released, maybe you try to change Hono with Elisya to see if mobius graphql client works in t4-app, so no need for Garph and Gqty and no need for codegen. The server is running on Yoga.

Homepage https://elysiajs.com
Author's twitter https://twitter.com/saltyAom

**Comment by timothymiller** [comment]
While I like bun, the ecosystem needs to be supported by Cloudflare before I'd consider adding it into the stack.

**Comment by geoman2** [comment]
Elysia framework just added support for workerd/cloudflare in version 0.6, here are the details https://twitter.com/saltyAom/status/1688233007407329280
Here https://twitter.com/honojs/status/1684839623355490304 is posted hono running on elysia and viceversa as both being winterCG compliant.
