### ISSUE TITLE
[Bug] Tanstack Table example doesn't work

### ISSUE THREAD

**Issue by albbus-stack** [timothymiller/t4-app#62]
The Tankstack Table example has an odd behaviour, I've tested this on web. 
It flashes the loaded content correctly for a second and then it disappears completely leaving the user with this screen without any table:

![2023-08-16 12_00_55-TanStack Table — Firefox Nightly](https://github.com/timothymiller/t4-app/assets/57916483/98540e02-1b7e-485b-9d8a-51ffabaaf9af)

The console shows the following errors:

![2023-08-16 11_56_49-](https://github.com/timothymiller/t4-app/assets/57916483/7ca96f58-5a45-4af5-bf03-2f022bf8bed3)

**Comment by timothymiller** [comment]
Works in local dev. Removed the link for now.
