### ISSUE TITLE
How is the shared code and `.native` // `.web` code merged if at all?

### ISSUE THREAD

**Issue by curdcorp** [timothymiller/t4-app#66]
Noobie question, but am wondering what the merge logic is for the various platform override code?

For example the demo mostly have `.tsx` and `.web.tsx`. Does this mean that the `.web.tsx` files somehow has `.tsx` components // logic? Or are they completely separate? 

Current intuition suggests that `.native.tsx` or `.web.tsx` will completely replace the `.tsx` file.

Would love to be pointed to any of the right package docs for more on this

**Comment by albbus-stack** [comment]
> Current intuition suggests that .native.tsx or .web.tsx will completely replace the .tsx file.

That is correct and the only thing you need to know really. 

The technical term is _tree shaking_ if you want to search more info about it, you can read https://solito.dev/recipes/tree-shaking since that's the one we use.
