### ISSUE TITLE
Support for bun?

### ISSUE THREAD

**Issue by wynnej1983** [timothymiller/t4-app#73]

**Comment by albbus-stack** [comment]
It should be pretty straightforward to implement, It also has a github action that we can use in the workflows

**Comment by hdwatts** [comment]
Bun doesn't play nicely with turbo as far as my initial testing is going

**Comment by albbus-stack** [comment]
> Bun doesn't play nicely with turbo as far as my initial testing is going

Oh okay didn't know about that, if you find out anything more please share it 🤟

**Comment by hdwatts** [comment]
> Oh okay didn't know about that, if you find out anything more please share it 🤟

Following up here - bun has been slowly fixing and improving it's workspace support! I have been using it to great success. However, there is at least one annoying thing left that's effecting me. If I change a package in any of my workspaces then `bun i` tries to install my workspace dependencies from npm (which naturally fails).

To resolve, I have to remove the `bun.lockb` file and re-install with `bun i`.

**Comment by timothymiller** [comment]
Totally. I see what you're saying. I made a branch named `bun` days ago, actually. It has the entire stack working fine, save for the database integration.

I'm thinking about removing turborepo entirely, as it adds extra complexity with little benefit with bun.

Give it a try!

**Comment by timothymiller** [comment]
These two issues track my work integrating bun into T4

https://github.com/cloudflare/workers-sdk/issues/3941
https://github.com/drizzle-team/drizzle-orm/issues/1224

**Comment by gunta** [comment]
> I'm thinking about removing turborepo entirely, as it adds extra complexity with little benefit with bun.

Definitely removing turborepo (either temporarily or not) is not gonna hurt, 
but adding support for bun would be good for this project PR and developer experience (overall performance).

When turborepo (or even better, [nx](https://nx.dev/) add support for bun, can consider adding it back later if necessary.

**Comment by albbus-stack** [comment]
@timothymiller Can we close this issue since bun support is out?

**Comment by Death666Machine** [comment]
> > I'm thinking about removing turborepo entirely, as it adds extra complexity with little benefit with bun.
> 
> Definitely removing turborepo (either temporarily or not) is not gonna hurt, but adding support for bun would be good for this project PR and developer experience (overall performance).
> 
> When turborepo (or even better, [nx](https://nx.dev/) add support for bun, can consider adding it back later if necessary.

https://jordan-hall.github.io/nx-bun/ 😁 if you're interested

**Comment by timothymiller** [comment]
So I added Bun support last week. I am working on removing turborepo entirely today.

FWIW building the t4/ui package is much faster without turborepo caching, even on cached "turbo" runs.

Still working on how to execute bun scripts in parallel, like the top level "dev", which runs bun web and bun api. If you have any suggestions, let me know.

**Comment by timothymiller** [comment]
The Bun migration is complete, and all CI/CD is showing green.

## Results:
- `34` second backend deploy times
- `1:43` frontend deploy times
- Replaced `turbo` with `run-p`
- 52ms cached `bun install` times
- 6 second `bun install` times on first run

**Comment by angel-luis** [comment]
Just a small consideration, @timothymiller you should remove turborepo from repo topics. Great job, I’m using this repo as a learning pathway and it’s very useful!
