### ISSUE TITLE
Supabase Google provider scope authorization error.

### ISSUE THREAD

**Issue by honeydreamssoftwares** [timothymiller/t4-app#76]
When logging in in the default T4 template after adding Supabase credentials in env the Google Auth fails with Authorization error.
![Sign-in-Google-Accounts](https://github.com/timothymiller/t4-app/assets/10350388/2b60a9ab-866e-4ddd-8337-64c9f91b47f1)

It seems that the scopes are provided in the file https://github.com/timothymiller/t4-app/blob/eaec461e0a69a8113a3d90bee25d868fcbd5cefb/packages/app/features/sign-in/screen.tsx  at line 18. I locally fixed the issue by adding `options: { scopes: 'https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile' },` since I plan to use only Google provider but that does not seem optimal solution as Supabase can have multiple providers each having its own unique scope.

Steps to reproduce
- Add Supabase credentials in the T4 template.
- Enable Google Auth from the Supabase Dashboard.
- Run app and log in with Google Sign in

Platform
Windows 11, WSL, Ubuntu 22, Node 18.

**Comment by timothymiller** [comment]
Thanks for the heads up.

I'm not clear if the other providers require a special scope passed to work.

It may be just a Google thing
