### ISSUE TITLE
Using only frontend part?

### ISSUE THREAD

**Issue by tonven** [timothymiller/t4-app#77]
Hi. I am backend developer with some expirience with React and almost zero experience with React Native. I have started on a side project where backend is already partially done and now I am starting on a frontend part which requires both web and native implementation. My question is how much effort can it take to replace backend and auth with a different stack? For example Firebase Auth will be used for auth and Azure services for backend (Azure functions as one of example). Thank you.

**Comment by albbus-stack** [comment]
I think the easiest way is to deploy your own backend and then use fetch to interact with it in the frontend.

Otherwise you could reimplement all of your backend inside trpc (packages/api).

Don't hesitate to get in touch on discord for further explanation
