### ISSUE TITLE
What are the recommended i18n framework for t4?

### ISSUE THREAD

**Issue by tonyabracadabra** [timothymiller/t4-app#87]

**Comment by masrurimz** [comment]
I'm using this one
https://github.com/ivanhofer/typesafe-i18n

**Comment by timothymiller** [comment]
@masrurimz Does that have a flash of un-translated text, or does SSR take care of displaying the correct translation?

If you could, a video of it working would be helpful.

**Comment by timothymiller** [comment]
typesafe-i18n it is!

**Comment by timothymiller** [comment]
I happened upon some rather sad news. Ivan Hofer, the maintainer of typesafe-i18n, recently passed away.

https://github.com/ivanhofer/typesafe-i18n/issues/739

It seems like his buddys are months away to a successor to that wonderful library called paraglide-js. No doubt this will be an ongoing topic.
