### ISSUE TITLE
supabaseUrl/imageUrl is required error being thrown until adding the `console.log` line

### ISSUE THREAD

**Issue by tonyabracadabra** [timothymiller/t4-app#90]
<img width="317" alt="image" src="https://github.com/timothymiller/t4-app/assets/6690727/7b6130a6-ab37-48ad-aa94-9de96ae90bfe">

I got the error above after filling in the env.local for the env variables,

interestingly, when I add a `console.log` in the file below, the error dissapears

```
import { createClient } from '@supabase/supabase-js'
import * as SecureStore from 'expo-secure-store'
import 'react-native-url-polyfill/auto'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL as string
// this is the line I added to make the error go away
console.log('print anything here')
```

I suppose there must be some env variable loading problems that causes this?

Similarly for `imageURL`

```
import { SolitoImageProvider as SolitoImageProviderOG } from 'solito/image'

const imageURL = process.env.NEXT_PUBLIC_APP_URL as `http:${string}` | `https:${string}`
// this is, again, the line I have to add to make the error go away
console.log('printanything')
```

**Comment by timothymiller** [comment]
We do need to add typing to the environment variables to make it clearer which ones are missing.

**Comment by rmarscher** [comment]
https://github.com/timothymiller/t4-app/pull/96 should fix this. The typescript cast syntax seemed to prevent the env vars from being replaced.

**Comment by albbus-stack** [comment]
@tonyabracadabra If you can please confirm that now it is working so we can close this issue. Thank you 🤟

**Comment by timothymiller** [comment]
Let's keep this open until we add typings to env vars access.

**Comment by albbus-stack** [comment]
@tonyabracadabra @rmarscher I implemented typesafe environment variables using `t3-env` in the latest PR #102. It would be great if you test that and let me know 🤘

**Comment by timothymiller** [comment]
I released three major features for T4 App today

👉 Android support for local API & Image access
👉 .env shim for unifying env vars across Expo, Next, and Cloudflare Wrangler
👉 Expo 49 support

Onboarding new users to the T4 App Stack has never been easier!
